In [2]:
#Example with python list
h=[1.71,1.58,1.67,1.89,1.73]
w=[67.9,78.8,56.8,49.3,73.2]
BMI=(w/h)**2
print(BMI)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [2]:
#Example with numpy array
h=[1.71,1.58,1.67,1.89,1.73]
w=[67.9,78.8,56.8,49.3,73.2]
import numpy as np
nh=np.array(h)
nw=np.array(w)
BMI=nw/nh**2
print(BMI)


[23.22082008 31.56545425 20.36645272 13.80140534 24.45788366]


### Speed check of numpy and python list

In [3]:
#Example with Python lists
l=range(1000)
%timeit [i**2 for i in l]

416 µs ± 23.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
#Example with numpy 
import numpy as np
a=np.arange(1000)
%timeit a**2

2.6 µs ± 159 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### creation of arrays

In [5]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
#to know dimensions
a.ndim

1

In [8]:
#to know number of rows and columns
a.shape

(6,)

In [9]:
#to know the length
len(a)

6

In [10]:
#2D,3D,4D...
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
b.ndim


2

In [12]:
b.shape

(2, 3)

In [17]:
b=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[4,5,6],[7,8,9]],[[10,11,12],[4,5,6],[7,8,9]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [ 4  5  6]
  [ 7  8  9]]]


In [18]:
b.ndim


3

In [19]:
#line space 
a=np.linespace(0,1,6)
print(a)

AttributeError: module 'numpy' has no attribute 'linespace'

In [20]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
c=np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#diagonal array
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [24]:
np.diag(a)

array([1, 2, 3])

In [25]:
#Create array using random
a=np.random.rand(4)
print(a)

[0.1451037  0.16917642 0.39445733 0.49006898]


In [26]:
b=np.random.randn(4)
print(b)

[ 1.11115266  0.07560458 -0.53062826  1.34067894]


In [1]:
import numpy as np
r=np.random.randint(20,36,4)
print(r)

[24 23 22 34]


# Basic Data Types:

In [2]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
a.dtype

dtype('int32')

In [4]:
b=np.arange(10,dtype='float64')
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
z=np.zeros(4)
print(z)

[0. 0. 0. 0.]


In [6]:
x=np.ones(4)
print(x)

[1. 1. 1. 1.]


In [7]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
y=np.eye(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
d=np.array([10.5+5j,20+6j])
print(d)

d.dtype

[10.+5.j 20.+6.j]


dtype('complex128')

In [10]:
#boolean data type
b=np.array([True,False,False,True])
print(b)
b.dtype

[ True False False  True]


dtype('bool')

In [11]:
#string type
s=np.array(["Akhila","Venky","Hello"])
s.dtype

dtype('<U6')

# Indexing & Slicing

## Indexing:

In [12]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(a[4])

4


In [14]:
#indexing in 2D array
b=np.diag([1,2,3,4])
print(b)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [15]:
print(b[2,2])

3


In [16]:
print(b[3,3])

4


In [17]:
b[3,2]=20
print(b)

[[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  3  0]
 [ 0  0 20  4]]


## slicing

In [18]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
#Using slicing
print(a[2:6])

[2 3 4 5]


In [20]:
print(a[0:10:2])

[0 2 4 6 8]


In [21]:
a[5:]=10
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [22]:
a[1]=20
print(a)

[ 0 20  2  3  4 10 10 10 10 10]


In [23]:
a[3:5]=99
print(a)

[ 0 20  2 99 99 10 10 10 10 10]


In [24]:
a=np.arange(10)
b=np.arange(5)
a[5:]=b[::-1]
print(a)


[0 1 2 3 4 4 3 2 1 0]


In [25]:
b=np.arange(10)
print(b[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [27]:
print(b[5::-1])
print(b)

[5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


# Copies and Views

A slicing operation creates a view on the original array, Which is just a way of accessing array data.

Thus the original array is not copied in memory. 

You can use np.may_share_memory() to check if two arrays shares the same memory block.


In [1]:
#Example program
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
b=a[::2]
print(b)

[0 2 4 6 8]


In [3]:
np.may_share_memory(a,b)

True

In [4]:
np.shares_memory(a,b)

True

In [5]:
b[0]=10
print(b)

[10  2  4  6  8]


In [6]:
print(a)

[10  1  2  3  4  5  6  7  8  9]


In [9]:
#example with copied data
a=np.arange(10)
c=a[::2].copy() #forced copy
print(c)
print(id(a))
print(id(c))

[0 2 4 6 8]
1707366565904
1707490197936


In [9]:
np.shares_memory(a,c)

False

In [10]:
c[0]=12
print(c)

[12  2  4  6  8]


In [11]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
l=[1,2,3,4,5]
print(id(l))
l1=l[1:4]
print(id(l1))

2409353504520
2409353504392


# Fancy Indexing:

In [ ]:
Numpy array can be indexed with slicing but also with boolean or integers(masks).

This method is called fancy indexing. It creats copies not views.

### Using Boolean masking:

In [13]:
a=np.random.randint(0,20,15)
print(a)

[ 0  5  7 11  2  2  7 17 11 13  0 15  5  2  8]


In [14]:
mask=(a%2==0)
extract_from_a=a[mask]
print(extract_from_a)


[0 2 2 0 2 8]


In [15]:
print(id(a))
print(id(extract_from_a))

2409374027824
2409374028144


In [16]:
a[mask]=-1
print(a)

[-1  5  7 11 -1 -1  7 17 11 13 -1 15  5 -1 -1]


In [17]:
a[mask]=99
print(a)

[99  5  7 11 99 99  7 17 11 13 99 15  5 99 99]


# Indexing with an array of integers:

In [18]:
a=np.arange(0,100,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [19]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [21]:
a[[9,7]]=-200
print(a)

[   0   10   20   30   40   50   60 -200   80 -200]


# NUmerical Operations on Numpy

In [ ]:
import numpy as np


#### Elementwise operations:

In [ ]:
1. Basic Operations:

In [22]:
a=np.array([1,2,3,4])
print(a)
a+1

[1 2 3 4]


array([2, 3, 4, 5])

In [23]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
Arithmetic operations elementwise:

In [24]:
b=np.ones(4)+1
print(b)

[2. 2. 2. 2.]


In [25]:
a-b

array([-1.,  0.,  1.,  2.])

In [26]:
a*b

array([2., 4., 6., 8.])

In [27]:
#matrix multiplication
c=np.diag([1,2,3,4])
print(c*c)


[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [28]:

print(c.dot(c)) #can also be used for matrix multiplication

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparisions

In [29]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b

array([False,  True, False,  True])

In [30]:
a>b

array([False, False,  True, False])

### Arraywise comparisions

In [31]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])
np.array_equal(a,b)

False

In [32]:
np.array_equal(a,c)

True

In [33]:
a=np.array([1,2,3,4])
b=np.array([1,2,5,4])

np.array_equal(a,b)

False

# logical operations

In [34]:
a=np.array([1,1,1,0], dtype='bool')
b=np.array([1,0,1,0],dtype='bool')
np.logical_or(a,b)

array([ True,  True,  True, False])

# Transcendental functions:

In [35]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [36]:
np.log(a)

C:\Users\venky\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [37]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# shape mismatch:

In [39]:
a=np.arange(10)
print(a)
a+np.array([2,4])

[0 1 2 3 4 5 6 7 8 9]


ValueError: operands could not be broadcast together with shapes (10,) (2,) 

# Basic Reductions

### cumputing sums:

In [40]:
x=np.array([1,2,3,4,5,6])
np.sum(x)

21

In [41]:
#sum of by rows and by columns
x=np.array([[1,2],[4,6]])
x

array([[1, 2],
       [4, 6]])

In [42]:
x.sum(axis=0) #column adding


array([5, 8])

In [43]:
x.sum(axis=1) #row adding

array([ 3, 10])

# Other reductions

In [1]:
import numpy as np
x=np.array([1,3,5,2])
x.min()

1

In [2]:
x.max()

5

In [3]:
x.argmax()

2

In [4]:
x.argmin()

0

# logical operations:

In [5]:
np.all([True,True,False,True])

False

In [6]:
np.all([True,True,True,True])

True

In [7]:
np.any([True,True,False,True])

True

In [8]:
np.any([True,False,False,False])

True

In [9]:
#can also be used for array comparisions
a=np.zeros((50,50))
np.any(a!=0)

False

In [10]:
np.all(a==a)

True

In [11]:
a=np.array([1,2,3,4])
b=np.array([4,2,3,6])
c=np.array([1,2,3,4])
((a<=b)&(b<=c)).all()

False

In [14]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [13]:
print(type(x))

<class 'numpy.ndarray'>


In [15]:
np.median(x)

1.5

In [16]:
np.median(y,axis=0)

array([3., 4., 2.])

In [17]:
np.median(y,axis=1)

array([2., 5.])

In [18]:
np.median(y)

2.5

In [19]:
x.std()

0.82915619758885

In [20]:
a=np.tile(np.arange(0,40,10),(3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [21]:
a=a.T
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [22]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [23]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [26]:
a=np.arange(0,40,10)
a.shape

(4,)

In [28]:
print(a)

[ 0 10 20 30]


In [29]:
a=a[:,np.newaxis]
a.shape

(4, 1)

In [30]:
print(a)

[[ 0]
 [10]
 [20]
 [30]]


In [31]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Flattening

In [32]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [33]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

# Reshaping

In [35]:
print(a.shape)

(2, 3)


In [36]:
print(a)

[[1 2 3]
 [4 5 6]]


In [38]:
b=a.ravel()

In [39]:
print(b)

[1 2 3 4 5 6]


In [40]:
b=b.reshape((2,3))

In [41]:
print(b)

[[1 2 3]
 [4 5 6]]


In [42]:
b[0,0]=100
print(b)

[[100   2   3]
 [  4   5   6]]


In [43]:
z=np.array([1,2,3])
print(z)

[1 2 3]


In [44]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [45]:
a=np.arange(4)

In [46]:
print(a)

[0 1 2 3]


In [47]:
a.resize(8)

In [48]:
print(a)

[0 1 2 3 0 0 0 0]


In [49]:
a=np.array([[5,4,6],[2,3,2]])
print(a)

[[5 4 6]
 [2 3 2]]


In [50]:
b=np.sort(a,axis=1)
print(b)

[[4 5 6]
 [2 2 3]]
